sudo: required
services:
  - docker

#BeforeInstall
before_install:
  - docker build -t jibolaolu/react-test -f ./client/Dockerfile.dev ./client

language: generic
script:
  - docker run -e CI=true jibolaolu/react-test npm test -- --coverage

after_success:
  - docker build -t jibolaolu/multi-client ./client
  - docker build -t jibolaolu/multi-nginx ./nginx
  - docker build -t jibolaolu/multi-server ./server
  - docker build -t jibolaolu/multi-worker ./worker

# Take Images to docker cli
  - echo "$Docker_password" | docker login -u "$Docker_id" --password-stdin

# Push Images to Docker hub

  - docker push jibolaolu/multi-client
  - docker push jibolaolu/multi-nginx
  - docker push jibolaolu/multi-server
  - docker push jibolaolu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-100753669199
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY

