sudo: required
services:
  - docker

#BeforeInstall
before_install:
  - docker build -t jibolaolu/react-test -f ./client/Dockerfile.dev ./client

language: generic
script:
  - docker run jibolaolu/react-test npm test -- --coverage

after_success:
  - docker build -t jibolaolu/multi-client ./client
  - docker build -t jibolaolu/multi-nginx ./nginx
  - docker build -t jibolaolu/multi-server ./server
  - docker build -t jibolaolu/multi-worker ./worker

# Take Images to docker cli
  - echo "$Docker_password" | docker login -u "$Docker_id" --password-stdin

# Push Images to Docker hub

  - docker push jibolaolu/multi-client
  - docker push jibolaolu/multi-nginx
  - docker push jibolaolu/multi-server
  - docker push jibolaolu/multi-worker

